# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    # Uncomment the following line to build your app if needed
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",export_method: "development" )


    # Upload app to App Store with additional app review information
    upload_to_app_store(
     username: "omar.nasser@ybservice.iq",
     app_identifier: "com.elt.productt.widgett",
      skip_metadata: false,
      skip_screenshots: false
    )
  end

end
